### ISSUE TITLE
Frontend problems 

### ISSUE THREAD

**Issue by gine78** [michbeck100/pimatic-dash-button#1]
Works good. I just toggle devices.
I block the dashbutton to communicate with Amazon - if there is no block, i have become a pushmessage on every klick that my device is not finaly installed.

Good job and thank you!

Edit: 
`Error [pimatic]: Error on incoming http request to /client-error: too many parameters`
This error appears since i have your Plugin installed.

Edit2: i just deaktivate the Plugin. I think, it destroy the pimatic mobile-frontend

`45error [pimatic-mobile-frontend]: Client error: TypeError: Unable to process binding "if: function (){return !$root.isGroupCollapsed($data,{id:'$ungrouped'}) }"
Message: Unable to process binding "template: function (){return { name:$root.getItemTemplate,foreach:$data.getUngroupedDevices(),afterRender:$data.afterRenderDevice} }"
Message: null is not an object (evaluating 'd')`

**Comment by michbeck100** [comment]
Can you tell when this happens? After pressing?

**Comment by gine78** [comment]
I installed the Plugin and restart pimatic. I dont know if the error comes when i press the Button, or it comes without Button. I try it

**Comment by gine78** [comment]
this appears when i start the webinterface. 

error [pimatic]: Error on incoming http request to /client-error: too many parameters

I dont have press the Button, i only activate the Plugin an the restart pimatic. If this Plugin ist active and i Start the webinterface the CSS looks not to be loaded.

**Comment by michbeck100** [comment]
What versions of pimatic and pimatic-mobile-frontend are you using? I don't get any errors when using pimatic-dash-button

**Comment by michbeck100** [comment]
Did you add the dash button as a device to your frontend? The dash button is not intended to be added to the frontend as there is nothing to show. It has no state or anything else. I’ll have a look into this error, though.

**Comment by gine78** [comment]
I think... that was the Problem. i have remove the button, now it works. 

Thank you.
