### ISSUE TITLE
Bug: Unable to process binding "template

### ISSUE THREAD

**Issue by mwittig** [michbeck100/pimatic-dash-button#2]
See also https://forum.pimatic.org/topic/2180/amazon-dash-button-plugin-available/3

Getting back to this, I can reproduce this problem, now. It occurs if the device had been added a to view page. When you do this you will see another error at first: Client error: Cannot read property '__ko__1473100260719' of null. After this the front-end will no longer properly render and you’ll get the other error. I think the reason is that you’re using a “templete” which is unkown in the frontend, i.e. “dashbutton”. It should be needed that the devices gets added to view though, so the error won’t disappear after restart. It can be resolved by opening the Configuration Editor to manually remove the device from the view.

I think the mobile frontend should be more robust against such errors. For the time being, users shall not add the DashButtonDevice to view pages.

**Comment by michbeck100** [comment]
Should be resolved with next release. I went a little bit further and enabled the dash button device in pimatic to be used in the GUI as a ButtonsDevice with one button.
