### ISSUE TITLE
[pimatic] error: Could not initialize the plugin "amazing-dash-button": device must be a string

### ISSUE THREAD

**Issue by n3roGit** [michbeck100/pimatic-dash-button#5]
i get this error after installing the plugin

**Comment by michbeck100** [comment]
Could you post your related parts of your config.json? Thats the plugins and devices sections

**Comment by n3roGit** [comment]
```
{
  "plugin": "amazing-dash-button",
  "active": true,
  "interfaceAddress": "192.168.1.13",
  "debug": true
}
```

but i think its my fail^^ i use the "amazong" plugin and not yours xD sorry!

**Comment by michbeck100** [comment]
Sorry, wrong plugin. This is for pimatic-dash-button. If you have problems using then head over to https://github.com/mwittig/pimatic-amazing-dash-button/issues or just use pimatic-dash-button ;-)
